### ISSUE TITLE
Unable to unpack Arm protection

### ISSUE THREAD

**Issue by Lohita9** [ZiTanIOI/newBlackDex#2]
@ZiTanIO I am using the latest version of newBlackDex. When I chose the ARM-protected APK, BlackDex generated the following [classes.dex](https://github.com/user-attachments/files/17762703/classes.zip) file, which is unusable. Please address this issue as soon as possible.

Here is the APK file for testing: [BN LAST KING OFFICIAL_1.0.zip](https://github.com/user-attachments/files/17762694/BN.LAST.KING.OFFICIAL_1.0.zip)

**Comment by ZiTanIOI** [comment]
I have update it,try the new version.

**Comment by Lohita9** [comment]
It is fixed now.

**Comment by Lohita9** [comment]
@ZiTanIOI Please fix these errors or deprecated during the completion of unpacking the arm protection. I have attached the log file for reference.

[top.niunaijun.blackdexa32_logcat.txt](https://github.com/user-attachments/files/17784807/top.niunaijun.blackdexa32_logcat.txt)

**Comment by ZiTanIOI** [comment]
I don't understand what went wrong. According to the log, the program has successfully obtained and decrypted the dex file.Is these dex file not useful?

**Comment by Lohita9** [comment]
I ask you to run lint in your android studio project. To address any memoryleak , deprecated code etc.

**Comment by Lohita9** [comment]
Can you unpack a unknown protection?

[Here is the original apk without encryption](https://github.com/user-attachments/files/17786341/AgeCalculator_0.0.0-alpha.zip)

[Here is the apk file with encryption](https://github.com/user-attachments/files/17786358/AgeCalculator_0.0.0-alpha_encrypted.zip)

**Comment by ZiTanIOI** [comment]
The encrypted app haven't signed ,signing it by my key ,then it can't run.Does it check its signature file?Or it doesn't support Android 14.

**Comment by ZiTanIOI** [comment]
The origin apk can run well.

**Comment by ZiTanIOI** [comment]
I try sign it and run on virtual app like vmos,it can run.It seems that this protection doesn't support Android 14.I just release blackdex to support Android 13 and 14.below them you can see the original version writen by niunai.I give the address in README file.

**Comment by Lohita9** [comment]
Okay
