### ISSUE TITLE
Add a feature to unpack jiagu 360 protection

### ISSUE THREAD

**Issue by Lohita9** [ZiTanIOI/newBlackDex#4]

**Comment by ZiTanIOI** [comment]
I am working on it now ,but 360 protection has a function to check self if running on virtual app like VA or blackbox/blackdex.I don't know how to pass it.

**Comment by Lohita9** [comment]
I have a frida script to unpack jiagu 360 protection.

Here is the frida script to dump jiagu 360 protection: [jiagu-360-dump.js](https://github.com/user-attachments/files/17775400/jiagu-360-dump.zip)

**Comment by ZiTanIOI** [comment]
Using the virtual app is different from the frida script with root,blackdex is like VMOS(I don't know if you have used it.An app used 360 protection can not run on it,too.).It creates a fake android environment to run the app.Frida script can inject in real Android system.360 protection check if itself is running on real system,if not, it will kill itself.That is the problem.The dump script only do dump work and don't hide the fake environment.

**Comment by ZiTanIOI** [comment]
When 360 protection think itself is safe then it begin loading dex file,if not it will not load dex file,then blackdex can not get the dex file.

**Comment by Lohita9** [comment]
@ZiTanIOI Please take a look at [this](https://github.com/ZiTanIOI/newBlackDex/issues/3) issue

**Comment by Lohita9** [comment]
I tried an app called Modder Hub, which is protected by Jiagu 360. Modder Hub worked normally in the VMOS app when I tested it seven days ago, but I uninstalled VMOS yesterday.

**Comment by ZiTanIOI** [comment]
I think it may be that the developer of the app unticked the function of detecting fake environments when uploading the app. Because 360 protection provides the developer with the freedom to choose whether to enable this feature.

**Comment by Lohita9** [comment]
@ZiTanIOI My friend send me this BlackDex apk having features 
(i) Advance DexDump optimised
(ii) Can Dump Latest 360 jigau, ijimai, bangbang protection etc

[[BETA]BlackDex_3.3.1.zip](https://github.com/user-attachments/files/17784270/BETA.BlackDex_3.3.1.zip)

**Comment by ZiTanIOI** [comment]
It is not helpful for me,the code of this app has a very deep confusion.My Android device can't even run this app properly.

**Comment by Lohita9** [comment]
That is true; the developer made the app code more confusing, which makes reverse engineering increasingly harder.
