### ISSUE TITLE
Posible open source code

### ISSUE THREAD

**Issue by MrIkso** [ZiTanIOI/newBlackDex#5]
Hi, possible open source for a future fork. Maybe other people will continue to work on this project when it is suspended

**Comment by ZiTanIOI** [comment]
Maybe,but not now. When I want to give up updating it ,I will upload source to github.

**Comment by Lohita9** [comment]
@ZiTanIOI I have the latest VirtualApp source. If you need it, I can share it with you to assist with BlackDex.

[classes.zip](https://github.com/user-attachments/files/18435042/classes.zip)
