### ISSUE TITLE
Add support to dump dex files of np.protect.assets.Shell2Applicationb protection

### ISSUE THREAD

**Issue by Lohita9** [ZiTanIOI/newBlackDex#6]
Here is the apk link: [VenKiT Obfuscator_1.4 (1).zip](https://github.com/user-attachments/files/17895090/VenKiT.Obfuscator_1.4.1.zip)

**Comment by ZiTanIOI** [comment]
I try run it on my two phone(Android 11 and Android 14),it crashed.It is impossible to dump dex files whitout running the app......

**Comment by Lohita9** [comment]
So I am closing this issue.
